import { Property, Yacht, Supercar, Event } from '@/types/database'

export const dummyProperties: Property[] = [
  {
    id: '1',
    title: 'Luxury Marina Villa with Private Pool',
    description: 'Stunning waterfront villa in Dubai Marina with breathtaking views and premium finishes.',
    price_aed: 8500000,
    property_type: 'villa',
    bedrooms: 5,
    bathrooms: 6,
    sqft: 6500,
    area: 'Dubai Marina',
    developer: 'Emaar Properties',
    crypto_verified: true,
    golden_visa_eligible: true,
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    ],
    amenities: ['Private Pool', 'Gym', 'Sauna', 'Smart Home', 'Sea View'],
    status: 'available',
    latitude: 25.0772,
    longitude: 55.1387,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Downtown Penthouse with Burj View',
    description: 'Exclusive penthouse in the heart of Downtown Dubai with direct Burj Khalifa views.',
    price_aed: 12000000,
    property_type: 'penthouse',
    bedrooms: 4,
    bathrooms: 5,
    sqft: 5800,
    area: 'Downtown Dubai',
    developer: 'Emaar Properties',
    crypto_verified: true,
    golden_visa_eligible: true,
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
    ],
    amenities: ['Private Elevator', 'Infinity Pool', 'Concierge', 'Valet', 'Burj View'],
    status: 'available',
    latitude: 25.1972,
    longitude: 55.2744,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Palm Jumeirah Beachfront Apartment',
    description: 'Sophisticated 3-bedroom apartment with direct beach access on the iconic Palm.',
    price_aed: 6750000,
    property_type: 'apartment',
    bedrooms: 3,
    bathrooms: 4,
    sqft: 3200,
    area: 'Palm Jumeirah',
    developer: 'Nakheel',
    crypto_verified: true,
    golden_visa_eligible: false,
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    ],
    amenities: ['Beach Access', 'Pool', 'Gym', 'Parking', 'Security 24/7'],
    status: 'available',
    latitude: 25.1124,
    longitude: 55.1390,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Arabian Ranches Modern Villa',
    description: 'Contemporary 4-bedroom villa in a family-friendly gated community with golf course.',
    price_aed: 4500000,
    property_type: 'villa',
    bedrooms: 4,
    bathrooms: 5,
    sqft: 4200,
    area: 'Arabian Ranches',
    developer: 'Emaar Properties',
    crypto_verified: true,
    golden_visa_eligible: false,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
    ],
    amenities: ['Garden', 'Pool', 'Golf Course Access', 'Kids Play Area', 'BBQ Area'],
    status: 'available',
    latitude: 25.0521,
    longitude: 55.2706,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Business Bay Luxury Townhouse',
    description: 'Modern 3-story townhouse with stunning canal views in Business Bay.',
    price_aed: 5200000,
    property_type: 'townhouse',
    bedrooms: 3,
    bathrooms: 4,
    sqft: 3800,
    area: 'Business Bay',
    developer: 'Damac Properties',
    crypto_verified: true,
    golden_visa_eligible: false,
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    ],
    amenities: ['Canal View', 'Rooftop Terrace', 'Maid Room', 'Storage', '2 Parking'],
    status: 'available',
    latitude: 25.1877,
    longitude: 55.2631,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Jumeirah Beach Residence Duplex',
    description: 'Spacious duplex with panoramic sea views and high-end finishes.',
    price_aed: 9800000,
    property_type: 'apartment',
    bedrooms: 4,
    bathrooms: 5,
    sqft: 4500,
    area: 'JBR',
    developer: 'Dubai Properties',
    crypto_verified: true,
    golden_visa_eligible: true,
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
    ],
    amenities: ['Sea View', 'Beach Access', 'Pool', 'Gym', 'Multiple Balconies'],
    status: 'available',
    latitude: 25.0778,
    longitude: 55.1324,
    created_at: new Date().toISOString(),
  },
]

export const dummyYachts: Yacht[] = [
  {
    id: '1',
    name: 'Majesty 100',
    description: 'Luxurious 100ft yacht perfect for parties and corporate events.',
    price_per_day_aed: 35000,
    length_ft: 100,
    guests_max: 25,
    yacht_type: 'Motor Yacht',
    images: ['https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800&q=80'],
    amenities: ['Jacuzzi', 'Jet Ski', 'Water Toys', 'Chef', 'Crew', 'Sound System'],
    whatsapp_booking: '+971501234567',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Ocean Pearl 75',
    description: 'Mid-size yacht ideal for family gatherings and small events.',
    price_per_day_aed: 22000,
    length_ft: 75,
    guests_max: 15,
    yacht_type: 'Motor Yacht',
    images: ['https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800&q=80'],
    amenities: ['Sun Deck', 'BBQ', 'Fishing Gear', 'Snorkeling', 'Crew'],
    whatsapp_booking: '+971501234567',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Azimut 58',
    description: 'Elegant yacht for intimate gatherings and romantic cruises.',
    price_per_day_aed: 15000,
    length_ft: 58,
    guests_max: 10,
    yacht_type: 'Motor Yacht',
    images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80'],
    amenities: ['Cabin', 'Kitchen', 'Sun Deck', 'Music System', 'Captain'],
    whatsapp_booking: '+971501234567',
    created_at: new Date().toISOString(),
  },
]

export const dummySupercars: Supercar[] = [
  {
    id: '1',
    brand: 'Lamborghini',
    model: 'Aventador SVJ',
    year: 2023,
    price_per_day_aed: 5500,
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'],
    specs: {
      engine: 'V12',
      horsepower: 770,
      topSpeed: '350 km/h',
      acceleration: '2.8s 0-100km/h',
      transmission: 'Automatic',
    },
    whatsapp_booking: '+971501234567',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    brand: 'Ferrari',
    model: 'F8 Tributo',
    year: 2023,
    price_per_day_aed: 4800,
    images: ['https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=800&q=80'],
    specs: {
      engine: 'V8 Twin-Turbo',
      horsepower: 710,
      topSpeed: '340 km/h',
      acceleration: '2.9s 0-100km/h',
      transmission: 'Automatic',
    },
    whatsapp_booking: '+971501234567',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    brand: 'Rolls-Royce',
    model: 'Cullinan',
    year: 2023,
    price_per_day_aed: 6500,
    images: ['https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=800&q=80'],
    specs: {
      engine: 'V12 Twin-Turbo',
      horsepower: 563,
      topSpeed: '250 km/h',
      acceleration: '5.0s 0-100km/h',
      transmission: 'Automatic',
      type: 'Luxury SUV',
    },
    whatsapp_booking: '+971501234567',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    brand: 'McLaren',
    model: '720S',
    year: 2023,
    price_per_day_aed: 4200,
    images: ['https://images.unsplash.com/photo-1621135802920-133df287f89c?w=800&q=80'],
    specs: {
      engine: 'V8 Twin-Turbo',
      horsepower: 710,
      topSpeed: '341 km/h',
      acceleration: '2.9s 0-100km/h',
      transmission: 'Automatic',
    },
    whatsapp_booking: '+971501234567',
    created_at: new Date().toISOString(),
  },
]

export const dummyEvents: Event[] = [
  // TODAY
  {
    id: '1',
    title: 'F1 Abu Dhabi Grand Prix - VIP Package',
    description: 'Experience the thrill of Formula 1 racing with exclusive VIP access. Includes paddock club access, meet & greet with drivers, and premium viewing.',
    price_aed: 15000,
    event_date: new Date().toISOString(),
    venue: 'Yas Marina Circuit',
    location: 'Abu Dhabi',
    category: 'Sports',
    images: ['https://images.unsplash.com/photo-1541443131876-44b03de101c5?w=800&q=80'],
    tickets_available: 50,
    source: 'PlatinumList',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Burj Khalifa New Year Gala 2026',
    description: 'Ring in the new year with breathtaking fireworks from the world\'s tallest building. Premium rooftop access with champagne and gourmet dining.',
    price_aed: 8500,
    event_date: new Date().toISOString(),
    venue: 'Burj Khalifa',
    location: 'Downtown Dubai',
    category: 'Entertainment',
    images: ['https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&q=80'],
    tickets_available: 200,
    source: 'Ticketmaster',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Dubai World Cup - Premium Seats',
    description: 'The world\'s richest horse race. VIP hospitality, gourmet dining, and prime trackside viewing for the ultimate racing experience.',
    price_aed: 12000,
    event_date: new Date().toISOString(),
    venue: 'Meydan Racecourse',
    location: 'Dubai',
    category: 'Sports',
    images: ['https://images.unsplash.com/photo-1534685785745-60a2cea0ec34?w=800&q=80'],
    tickets_available: 75,
    source: 'PlatinumList',
    created_at: new Date().toISOString(),
  },
  // THIS WEEK
  {
    id: '4',
    title: 'Drake Live in Dubai',
    description: 'Multi-platinum artist Drake brings his world tour to Dubai. Floor seats with VIP afterparty access included.',
    price_aed: 2500,
    event_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    venue: 'Coca-Cola Arena',
    location: 'Dubai',
    category: 'Music',
    images: ['https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&q=80'],
    tickets_available: 500,
    source: 'Ticketmaster',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'White Dubai - Calvin Harris',
    description: 'Legendary DJ Calvin Harris performing an exclusive set at Dubai\'s premier nightclub. Table service and bottle packages available.',
    price_aed: 1800,
    event_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    venue: 'White Dubai',
    location: 'Dubai',
    category: 'Nightlife',
    images: ['https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80'],
    tickets_available: 300,
    source: 'PlatinumList',
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Dubai Opera: Swan Lake Ballet',
    description: 'World-class ballet performance by the Bolshoi Theatre. Experience classical elegance in Dubai\'s stunning opera house.',
    price_aed: 950,
    event_date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    venue: 'Dubai Opera',
    location: 'Downtown Dubai',
    category: 'Arts & Culture',
    images: ['https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=800&q=80'],
    tickets_available: 150,
    source: 'Ticketmaster',
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    title: 'Atlantis Aquaventure VIP Day Pass',
    description: 'Exclusive VIP access to Dubai\'s #1 waterpark. Skip all lines, private cabana, and unlimited food & beverages.',
    price_aed: 1200,
    event_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    venue: 'Atlantis The Palm',
    location: 'Palm Jumeirah',
    category: 'Entertainment',
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80'],
    tickets_available: 100,
    source: 'PlatinumList',
    created_at: new Date().toISOString(),
  },
  // NEXT WEEK AND BEYOND
  {
    id: '8',
    title: 'Dubai Yacht Club Grand Regatta',
    description: 'Annual sailing competition with VIP yacht party. Network with Dubai\'s elite while enjoying champagne and canapés.',
    price_aed: 3500,
    event_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    venue: 'Dubai Marina Yacht Club',
    location: 'Dubai Marina',
    category: 'Sports',
    images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80'],
    tickets_available: 80,
    source: 'PlatinumList',
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    title: 'Michelin Star Chef Dinner Experience',
    description: 'Exclusive 10-course tasting menu by three Michelin-starred Chef. Wine pairing included. Limited to 30 guests.',
    price_aed: 2800,
    event_date: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    venue: 'Burj Al Arab',
    location: 'Jumeirah',
    category: 'Dining',
    images: ['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80'],
    tickets_available: 30,
    source: 'PlatinumList',
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    title: 'Dubai International Boat Show VIP',
    description: 'Premium access to the region\'s biggest marine exhibition. Private yacht tours and networking with industry leaders.',
    price_aed: 1500,
    event_date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    venue: 'Dubai Harbour',
    location: 'Dubai',
    category: 'Exhibition',
    images: ['https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800&q=80'],
    tickets_available: 250,
    source: 'Ticketmaster',
    created_at: new Date().toISOString(),
  },
  {
    id: '11',
    title: 'Private Jet & Supercar Showcase',
    description: 'Exclusive exhibition of the world\'s most luxurious vehicles. Test drives available for supercars. Networking event.',
    price_aed: 2200,
    event_date: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    venue: 'Dubai World Trade Centre',
    location: 'Dubai',
    category: 'Exhibition',
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'],
    tickets_available: 300,
    source: 'PlatinumList',
    created_at: new Date().toISOString(),
  },
  {
    id: '12',
    title: 'Dubai Jazz Festival - Weekend Pass',
    description: 'Two days of world-class jazz performances featuring international artists. VIP lounge access and meet & greet.',
    price_aed: 1650,
    event_date: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    venue: 'Dubai Media City Amphitheatre',
    location: 'Dubai',
    category: 'Music',
    images: ['https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800&q=80'],
    tickets_available: 400,
    source: 'Ticketmaster',
    created_at: new Date().toISOString(),
  },
]
